learning_templates/base_app/urls.py
from django.urls import path, include
from base_app import views

app_name = "base_app"
urlpatterns = [
    path('relative/', views.relative, name = "relative"),
    path('other/', views.other, name = "other"),

]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from base_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name = "index"),
    path('base_app/', include('base_app.urls')),
]

learning_templates/base_app/models.py
from django.db import models

# Create your models here.

learning_templates/base_app/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context_dict = {'text': "hello world", 'number': 100}
    return render(request, "index.html", context_dict)

def other(request):
    return render(request, "other.html")

def relative(request):
    return render(request, "relative_url_templates.html")

learning_templates/base_app/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>BASE</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'index' %}">BRAND <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'admin:index' %}">ADMIN</a>
      </li>
          <li><a class="navbar-brand" href="{% url 'base_app:other' %}">OTHER</a></li>
        </ul>
    </nav>

<div class="container">

{% block body_block %}

{% endblock %}
</div>
  </body>
</html>

learning_templates/base_app/templates/index.html
<!DOCTYPE html>
{% extends "base.html" %}

{% block body_block %}
<h1>Wellcome to Home Page</h1>
<!-- <h2>this is also an example</h2> -->
<h1>{{ text|cut:'hello' }}</h1>
<h1>{{ number|add:"99" }}</h1>

{% endblock %}

learning_templates/base_app/templates/other.html
<!DOCTYPE html>
{% extends "base.html" %}

    {% block body_block %}
    <h1>Wellcome to Other Page</h1>
    <h2>this is example of templates inheritance</h2>
    {% endblock %}

learning_templates/base_app/templates/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
<h1>Wellcome to Relative URL Templates</h1>
<a href="{% url 'base_app:other' %}">OTHER</a>
<a href="{% url 'admin:index' %}">ADMIN</a>
<a href="{% url 'index' %}">Index</a>
  </body>
</html>